version: '3.1'

services:

  mongo-orders:
    image: mongo
    ports:
      - 27019:27019
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: senha12345678    

  mongo-express-orders:
    image: mongo-express
    ports:
      - 8083:8083
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: senha12345678
      ME_CONFIG_MONGODB_PORT: 27019